<?php
/**
 * Koowa
 *
 * @package		Crossinghippos_Koowa
 * @author		Babs Gösgens/Crossing Hippos (https://crossinghippos.com)
 * @copyright   Copyright (c) 2011 Babs Gösgens/Crossing Hippos (https://crossinghippos.com)
 * @license		Open Software License
 */
?>
<h1>Koowa View Module</h1>
<?php
//var_dump($this->getView()->createRoute());
//var_dump($this->getView()->getMethods());
//var_dump($this->getView()->getTemplate()->getMethods());
//var_dump($this->getView()->getTemplate()->getView());
?>
<?php echo $this->getView()->display() ?>